pypi:
    script:
        - cp /keys/.pypirc ~/.pypirc
        - virtualenv env
        - source env/bin/activate
        - XDG_CACHE_HOME=/cache pip3 install -U pip setuptools wheel
        - XDG_CACHE_HOME=/cache pip3 install -r requirements_dev.txt
        - python setup.py sdist develop
        - python setup.py sdist clean
        - python setup.py sdist upload
        - python setup.py bdist_wheel upload
    tags:
        - python3
    only:
        - pypi
    artifacts:
        paths:
            - dist/
