language: python
install:
  - pip install tox
dist: trusty
sudo: required
before_script:
  - ./.travis-install-db.sh
script:
  - tox
services:
  - docker
  - postgresql
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=style
addons:
  postgresql: "9.4"

