# Generated by Django 2.1.4 on 2018-12-16 15:30
import pgrowcrypt.models.fields
from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CryptoExtension(),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', pgrowcrypt.models.fields.EncryptedTextField()),
            ],
        ),
    ]
